# Generated by Django 4.2 on 2023-06-04 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_remove_cartmembers_product_cartmembers_product'),
        ('guestWebsite', '0001_initial'),
        ('seller', '0002_alter_sellerprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='reqClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.cartmembers')),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guestWebsite.goods_for_sale')),
            ],
        ),
    ]
