# Generated by Django 4.2 on 2023-06-04 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_reqclient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reqclient',
            name='product',
        ),
    ]
