# Generated by Django 4.2 on 2023-06-03 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guestWebsite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0002_membersprofile_quantity_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membersprofile',
            name='quantity_cart',
        ),
        migrations.CreateModel(
            name='cartMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_cart', models.IntegerField(blank=True, default=1)),
                ('Total_per_product', models.FloatField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='guestWebsite.goods_for_sale')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
