# Generated by Django 4.2 on 2023-06-03 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_cartmembers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmembers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.membersprofile'),
        ),
    ]
