# Generated by Django 4.2 on 2023-06-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestWebsite', '0001_initial'),
        ('members', '0005_alter_cartmembers_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmembers',
            name='product',
        ),
        migrations.AddField(
            model_name='cartmembers',
            name='product',
            field=models.ManyToManyField(to='guestWebsite.goods_for_sale'),
        ),
    ]
