# Generated by Django 4.2 on 2023-06-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestWebsite', '0001_initial'),
        ('members', '0006_remove_cartmembers_product_cartmembers_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmembers',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='productss', to='guestWebsite.goods_for_sale'),
        ),
    ]
