# Generated by Django 4.2 on 2023-06-03 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guestWebsite', '0001_initial'),
        ('members', '0007_alter_cartmembers_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmembers',
            name='product',
        ),
        migrations.AddField(
            model_name='cartmembers',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guestWebsite.goods_for_sale'),
        ),
    ]
