# Generated by Django 4.2 on 2023-06-05 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_remove_cartmembers_product_cartmembers_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmembers',
            name='quantity_cart',
            field=models.FloatField(blank=True, default=1),
        ),
    ]
